version: "3.8"
# change major to Java major version, i.e. 8,11
services:

  java11:
    build:
      context: .
      args:
        - major=11
    image: local/java:11
    volumes:
      - ~/volumes/java11.local/log:/data/log
      - ~/volumes/java11.local/persist:/data/persist
    env_file:
      - ./env
    environment:
      - LCS_LOG_LEVEL=debug
    secrets:
      - lcs
    hostname: java11.local
    container_name: java11.local

  java8:
    build:
      context: .
      args:
        - major=8
    image: local/java:8
    volumes:
      - ~/volumes/java8.local/log:/data/log
      - ~/volumes/java8.local/persist:/data/persist
    env_file:
      - ./env
    secrets:
      - lcs
    hostname: java8.local
    container_name: java8.local

secrets:
  lcs:
    file: ~/.vcubi/lcs
