version: "3.7"
# change major to JRE major version, i.e. 9,10,11
services:

  jre13: # glibc version
    build:
      context: .
      dockerfile: Dockerfile.jre13
      args:
        - version=13.33
        - build=dev
    image: leadstec/jre:13.33
    volumes:
      - ~/volumes/jre13.local/log:/data/log
      - ~/volumes/jre13.local/persist:/data/persist
    env_file:
      - .env
    secrets:
      - lcs
    hostname: jre13.local
    container_name: jre13.local

  jre11:
    build:
      context: .
      args:
        - version=11.0.5
        - build=dev
    image: leadstec/jre:11.0.5
    volumes:
      - ~/volumes/jre11.local/log:/data/log
      - ~/volumes/jre11.local/persist:/data/persist
    env_file:
      - ./env
    environment:
      - EMAIL=
      - LCS_LOG_LEVEL=debug
    secrets:
      - lcs
    hostname: jre11.local
    container_name: jre11.local

  jre10:
    build:
      context: .
      args:
        - version=10.0.2
        - build=dev
    image: leadstec/jre:10.0.2
    volumes:
      - ~/volumes/jre10.local/log:/data/log
      - ~/volumes/jre10.local/persist:/data/persist
    env_file:
      - ./env
    secrets:
      - lcs
    hostname: jre10.local
    container_name: jre10.local

  jre9:
    build:
      context: .
      args:
        - version=9.0.4
        - build=dev
    image: leadstec/jre:9.0.4
    volumes:
      - ~/volumes/jre9.local/log:/data/log
      - ~/volumes/jre9.local/persist:/data/persist
    env_file:
      - ./env
    secrets:
      - lcs
    hostname: jre9.local
    container_name: jre9.local

  jre8:
    build:
      context: .
      dockerfile: Dockerfile.jre8
      args:
        - version=8.232.09
        - build=dev
    image: leadstec/jre:8.232.09
    volumes:
      - ~/volumes/jre8.local/log:/data/log
      - ~/volumes/jre8.local/persist:/data/persist
    env_file:
      - ./env
    secrets:
      - lcs
    hostname: jre8.local
    container_name: jre8.local

secrets:
  lcs:
    file: ~/.vcubi/lcs
