#!/bin/bash

set -e

clog -t "java: Build process starts ..."

# add image schema
lcs-cli schema add --section java

# Create profile for global env in different shells
cat > /etc/profile.d/java.sh <<EOF
export JAVA_HOME=${JAVA_HOME}
export LANG=${LANG}
EOF
clog -i "java: Global ENVs added to /etc/profile.d"

clog -t "java: Build process completed."
